### ISSUE TITLE
Please release latest version to CPAN

### ISSUE THREAD

**Issue by davorg** [tokuhirom/HTML-Escape#8]
I see you merged a PR that improved the documentation (https://github.com/tokuhirom/HTML-Escape/pull/6), but this fix hasn't yet made it onto CPAN.

I've just seen [a discussion on StackOverflow](https://stackoverflow.com/questions/69288616/displaying-html-in-perl-tag) where a user is confused by your documentation and I think the fixes in that PR would really help.

Could you please release the latest version to CPAN?

(If you're no longer interested in maintaining this module, then perhaps you'd consider giving me COMAINT rights so that I can take it over.)

**Comment by tokuhirom** [comment]
Oops. I shipped a new version!
Thanks for your notification.
